### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by codecorsair** [CUModSquad/SquadBot#29]
Squadbot crashed today.  Here's the message he output when he crashed:

>/home/bitnami/SquadBot/cu-squadbot.js:1676
          server.lastStanza = epochTime;
                              ^
ReferenceError: epochTime is not defined
    at Client.<anonymous> (/home/bitnami/SquadBot/cu-squadbot.js:1676:31)
    at Client.emit (events.js:107:17)
    at Client.<anonymous> (/home/bitnami/SquadBot/node_modules/node-xmpp/node_modules/node-xmpp-client/index.js:184:33)
    at Connection.emit (events.js:129:20)
    at TLSSocket.onDisconnect (/home/bitnami/SquadBot/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/reconnect-core/index.js:59:17)
    at TLSSocket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by sysrage** [comment]
Holy cow. I never saw this when you sent it. Guess I need to turn on e-mail notifications or something. Thanks for the report, I'll look into it.

**Comment by sysrage** [comment]
As far as I can tell, this is now fixed. There was no good reason for that code, so it was just removed. Let me know if any more crashes are seen or if the bot just stops responding.

**Comment by codecorsair** [comment]
:+1:
